spring.application.name=spendwise-api
spring.datasource.url=jdbc:postgresql://127.0.0.1:55432/spendwise
spring.datasource.username=spendwise
spring.datasource.password=spendwise
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

