CREATE TABLE transactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users (id),
    category_id BIGINT NOT NULL REFERENCES categories (id),
    amount      NUMERIC(12, 2) NOT NULL,
    date        DATE NOT NULL,
    note        VARCHAR(255),
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
